#!/bin/bash
echo "deb http://us.archive.ubuntu.com/ubuntu/ oneiric main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ oneiric-updates main restricted universe multiverse

deb http://us.archive.ubuntu.com/ubuntu/ oneiric-backports main restricted universe multiverse

deb http://archive.canonical.com/ubuntu oneiric partner

deb http://extras.ubuntu.com/ubuntu oneiric main" > /etc/apt/sources.list

apt-get install -y vim wget
sh -c 'echo "deb http://packages.ros.org/ros/ubuntu oneiric main" > /etc/apt/sources.list.d/ros-latest.list'
wget http://packages.ros.org/ros.key -O - | apt-key add -
apt-get update
apt-get install -y ros-fuerte-desktop-full ros-fuerte-joystick-drivers
chown -R 1234 /opt/ros/*/

