#!/bin/bash

sh -c 'echo "deb http://packages.ros.org/ros/ubuntu maverick main" > /etc/apt/sources.list.d/ros-latest.list'
wget http://packages.ros.org/ros.key -O - | apt-key add -
apt-get update
yes | apt-get install ros-diamondback-desktop-full ros-diamondback-joystick-drivers
exit
